#pragma config(Sensor, S1,     LightSensor,    sensorEV3_Color)
#pragma config(Sensor, S3,     Gyro,           sensorEV3_Gyro, modeEV3Gyro_Rate)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
  //Resets the gyro on port 2 to 0 degrees
  resetGyro(S3);
  while(true)
  {
    //Keep looping until the gyro sensor reads greater
    //than 90 degrees from its current position
    while(getGyroDegrees(S3) < 90)
    {
      //Point turn to the left
      setMotorSpeed(motorC, -25);
      setMotorSpeed(motorB, 25);
    }

    //Stop the motors at the end of the turn
    setMotorSpeed(motorB, 15);
    setMotorSpeed(motorC, 15);
  }
}